extends Resource
class_name VolumeSettings

@export var SlidersVulumeSettings = {
	"VolumenMamushkas" : 0,
	"intro1Mamushka": 6,
	"intro2Mamushka": -7,
	"intro3Mamushka": -9, 
	"intro4Mamushka" :0, 
	"abrirMamushka":4, 
	"cerrarVacioMamuska":4, 
	"cerrarIncorrectoMamushka":4,
	"naranjaCorrecto" : 1,
	"verdeCorrecto": -6,
	"marronCorrecto":-6,
	"azulCorrecto":4,
	"agarrarMamushka":0,
	"soltarMamushka":2,
	"azulSeVaMamushka":2,
	"finalCapasATierraMamushka":-9,
	"VolumenTransformaciones" : 0,
	"avalancha" : 0,
	"terremotos":0,
	"sedimentaria":0,
	"lavaLoop":0,
	"lavaAparece":0,
	"metamorfica":0,
	"plutonica":0,
	"explosion":0,
	"volcanica":0,
	"tramo1":0,
	"caraAparece":0,
	"nubeRecuerdo":0,
	"VolumenDondeEstuvo" : 0,
	"puerta": 0,
	"casco": 0,
	"guante1": 0,
	"guante2": 0,
	"guanteCae": 0,
	"globoNieve": 0,
	"jetpack": 0,
	"campera": 0,
	"pantalon": 0,
	"bota2": 0,
	"botaCae": 0,
	"reloj": 0,
	"cucarachaPiso": 0,
	"cucarachaPuerta": 0
	}
