extends Resource
class_name VolumeSettings

@export var SlidersVulumeSettings = {
	"VolumenMamushkas" : 0,
	"intro1Mamushka": 6,
	"intro2Mamushka": -7,
	"intro3Mamushka": -9, 
	"intro4Mamushka" :0, 
	"abrirMamushka":4, 
	"cerrarVacioMamuska":4, 
	"cerrarIncorrectoMamushka":4,
	"naranjaCorrecto" : 1,
	"verdeCorrecto": -6,
	"marronCorrecto":-6,
	"azulCorrecto":4,
	"agarrarMamushka":0,
	"soltarMamushka":2,
	"azulSeVaMamushka":2,
	"finalCapasATierraMamushka":-9,
	"VolumenTransformaciones" : 0,
	"avalancha" : -3,
	"terremotos":-5,
	"sedimentaria":-5,
	"lavaLoop":6,
	"lavaAparece":0,
	"metamorfica":1,
	"plutonica":3,
	"explosion":0,
	"volcanica":-3,
	"tramo1":0,
	"caraAparece":0,
	"nubeRecuerdo":-8,
	"VolumenDondeEstuvo" : 0,
	"puerta": -15,
	"casco": -10,
	"guante1": -10,
	"guante2": -10,
	"guanteCae": -2,
	"globoNieve": 0,
	"jetpack": -7,
	"campera": -10,
	"pantalon": -10,
	"bota1":-10,
	"bota2": -8,
	"botaCae": -10,
	"reloj": 0,
	"cucarachaPiso": 0,
	"cucarachaPuerta": 0,
	"laserLoop": -22,
	"laserCorrecto":-11,
	"laserIncorrecto":-16,
	"noPista":4,
	"pistaEncontrada":-10,
	"planetasAparecen": -6,
	"planetasSeVan": -11,
	"planetasUnidosSeAcomodan": -8,
	"VolumenAstronauta": 0,
	"jetPack": -7,
	"pedo": -19,
	"astronautaRespiracion": -2,
	"agarrar":0,
	"otrosAstronautas":-9,
	"salidaCueva":0,
	"CHIPA":0,
	"CHIPAPrende":0,
	"choqueMeteoro" : -2,
	"golpe":0,
	"FigtherVolumen":0,
	"luzEnciende": -6,
	"nombreAparece":-2,
	"eleccion":4,
	"explosionPiedra":-5,
	"ups": -12,
	"peleaCorrecta": -8,
	"finalFigthter": -13,
	"publico":0,
	"CalendarioVolumen":0,
	"cierreCirculo":-5,
	"apareceMemoria":0,
	"apareceFoto":0,
	"signoPregunta":0,
	"zoomIn":-6,
	"zoomOut":0,
	"tocarOpcion":0,
	"swipeOpcion":0,
	"opcionCorrecta":0,
	"incorrecto1":0,
	"incorrecto2":0,
	"zoomOutOutro":-10,
	"VolumenIntroScroll": 0,
	"musicLoop":-10,
	"musicIntro":-10,
	"entraTitulo":0,
	"islaAcerca":6,
	"swipeIslas": 0,
	"chan": -8,
	"pointersAparecen":-13,
	"correrMapa":0,
	"tocarNaumi":0,
	"TopoNivelVolumen":0,
	"topoGuia": 0,
	"tocoTopo": 0,
	"topoLoop": -18,
	"explosionFosil":-16,
	"explosionObjeto":-21,
	"enciclopedia":-12,
	"pincel":-4,
	"lapiz":-4,
	"dibujando":-10,
	"pintando":-5,
	"pintando2":-5,
	"FoodtruckVolumen":0,
	"arbustos":-19,
	"burbujaHabla":-6,
	"bandejaEntra":-5,
	"bandejaSale":-2,
	"tocoPlato": 3,
	"deslizoPlato": 4,
	"dejoPlato":0,
	"smilodonteEntra":-7,
	"smilodonteReclama":0,
	"smilodonteCorrecto":0,
	"gliptodonteEntra":0,
	"gliptodonteReclamo":0,
	"gliptodonteCorrecto":0,
	"megaterioEntra":-7,
	"megaterioReclamo":0,
	"megaterioCorrecto":-6,
	"macrauqueniaEntra":-4,
	"macrauqueniaReclamo":0,
	"macrauqueniaCorrecto":0,
	"platoIncorrecto":-8,
	"dejanPropina":-11,
	"agarroPropina":-10,
	"servilleta":-5,
	"estrellas":-12,
	"aparecePiolin":-7,
	"tapPiolin":0,
	"intentoCerrarReja":-4,
	"cerrarReja":-11,
	"mapaYviento":0,
	"mapaGira":0,
	"vientoLoop":0,
	"BusquedaVolume":0,
	"hinchada":-16,
	"patitaEspera":0,
	"pensamientoAparece":0,
	"pensando":0,
	"elijo":0,
	"tribunaCorrecto":0,
	"tribunaIncorrecta":0,
	"naumiTap":0,
	"naumiZZZ":0,
	"golpeNaumi1":0,
	"golpe2Naumi1":0,
	"rompeNaumi1":0,
	"golpeNaumi2":0,
	"rompeNaumi2":0,
	"golpeNaumi3":0,
	"rompeNaumi3":0,
	"aparicionBubble":6,
	"TypingBubble":6,
	"swipeRapido":0,
	"swipeLento":-6,
	"unlockIslands":-16
	}
